apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: default
stringData:
  prometheus-additional.yaml: 
    - job_name: falco_exporter 
    static_configs: 
      metrics_path: /metrics
        - targets: ["127.0.0.1:9376"] 
type: Opaque