apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: default
  name: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus-grafana
  additionalScrapeConfigs:
    name: "additional-scrape-configs"
    key: "prometheus-additional.yaml"
  serviceMonitorSelector: {}