apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: additional-scrape-configs
stringData:
  prometheus-additional.yaml: |
    - job_name: "falco-exporter"
      static_configs:
      - targets: ["127.0.0.1:9376"]